name: PHP Linting

on: pull_request

jobs:

  php-lint:
    runs-on: ubuntu-latest

    steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Check PHP Lint
          uses: michaelw90/PHP-Lint@master
